# Generated by Django 2.2.16 on 2020-10-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartgov', '0002_auto_20201020_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='outcomedata',
            old_name='data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='outputdata',
            old_name='data',
            new_name='value',
        ),
    ]
