# Generated by Django 2.2.16 on 2020-10-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartgov', '0003_auto_20201020_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydataset',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='entrydataset',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='entrydataset',
            name='outputs',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartgov.EntryDataset'),
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartgov.EntryDataset'),
        ),
        migrations.AddField(
            model_name='outputdata',
            name='entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartgov.EntryDataset'),
        ),
    ]
