# Generated by Django 2.2.16 on 2020-10-26 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartgov', '0004_auto_20201020_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrydataset',
            options={'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='inputdata',
            options={'verbose_name': 'Input Data', 'verbose_name_plural': 'Input Data'},
        ),
        migrations.AlterModelOptions(
            name='outcomedata',
            options={'verbose_name': 'Outcome Data', 'verbose_name_plural': 'Outcome Data'},
        ),
        migrations.AlterModelOptions(
            name='outputdata',
            options={'verbose_name': 'Output Data', 'verbose_name_plural': 'Output Data'},
        ),
        migrations.AddField(
            model_name='dataset',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Value (%)'),
        ),
        migrations.AlterField(
            model_name='outcomedata',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Value (%)'),
        ),
        migrations.AlterField(
            model_name='outputdata',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Value (%)'),
        ),
    ]
